properties:
  object_detection.png:
    type: binary
    format: image/png
    x-yamlover:
      concrete: file/binary
  markup:
    type: array
    prefixItems:
      - type: object
        description: bus
        properties:
          x:
            const: 25
          y:
            const: 40
          dx:
            const: 25
          dy:
            const: 40
      - type: object
        description: car
        properties:
          x:
            const: 25
          y:
            const: 40
          dx:
            const: 25
          dy:
            const: 40
