//! Differential gate: this implementation must agree with `tools/parser/ts`, exactly.
//!
//! `tools/jetbrains-plugin/README.md` names this harness as the missing piece for its Kotlin
//! port — "a golden-token parity harness (dumps generated from highlight.ts asserted against
//! the Kotlin lexers, with a CI drift trip-wire) is the planned follow-up". A second
//! implementation is only an oracle if something forces the two to agree; this is that
//! something, for the writer half.
//!
//! The golden is generated by `tests/gen-ts-parity.mjs` and committed. Regenerate with:
//!
//! ```sh
//! node tools/parser/rust/tests/gen-ts-parity.mjs > tools/parser/rust/tests/ts-parity.json
//! ```
//!
//! A diff in that file is a REAL event: either the TS law moved (and this port must follow)
//! or someone changed it by accident.

use serde_json::Value as J;
use std::path::PathBuf;

use yamlover_parser::ir::ScalarValue;
use yamlover_parser::pointer::key_portion;
use yamlover_parser::scalar::{fold_lines, plain_scalar, split_kv, unquote_key};
use yamlover_parser::serialize_common::{dq, flow_key_text, key_text};

fn golden() -> J {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/ts-parity.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("ts-parity.json is not valid JSON")
}

/// Collects divergences so one run reports every one of them, not just the first.
#[derive(Default)]
struct Diff(Vec<String>);

impl Diff {
    fn check(&mut self, what: &str, input: &str, got: &str, want: &str) {
        if got != want {
            self.0.push(format!(
                "  {what}({input:?})\n    ts:   {want:?}\n    rust: {got:?}"
            ));
        }
    }

    fn finish(self, section: &str) {
        assert!(
            self.0.is_empty(),
            "{} divergence(s) from tools/parser/ts in `{section}`:\n{}",
            self.0.len(),
            self.0.join("\n")
        );
    }
}

fn obj<'a>(g: &'a J, section: &str) -> &'a serde_json::Map<String, J> {
    let o = g[section]
        .as_object()
        .unwrap_or_else(|| panic!("the golden has no `{section}` section — regenerate it"));
    assert!(!o.is_empty(), "the `{section}` corpus is empty");
    o
}

#[test]
fn escaping_laws_match_the_typescript_implementation() {
    let g = golden();
    let mut d = Diff::default();
    for (input, want) in obj(&g, "escaping") {
        let s = |f: &str| want[f].as_str().unwrap_or_else(|| panic!("missing {f} for {input:?}"));
        d.check("keyText", input, &key_text(input), s("keyText"));
        d.check("flowKeyText", input, &flow_key_text(input), s("flowKeyText"));
        d.check("keyPortion", input, &key_portion(input), s("keyPortion"));
        d.check("dq", input, &dq(input), s("dq"));
    }
    d.finish("escaping");
}

/// Render a `ScalarValue` in the golden's tagged encoding so the two sides compare as text.
/// `canon.ts` uses the same sentinels, and for the same reason: JSON holds neither NaN,
/// ±Infinity nor -0.
fn encode(v: &ScalarValue) -> String {
    match v {
        ScalarValue::Null => "null".to_string(),
        ScalarValue::Bool(b) => format!("bool:{b}"),
        ScalarValue::Str(s) => format!("str:{s}"),
        ScalarValue::Num(n) => {
            if n.is_nan() {
                "num:nan".to_string()
            } else if *n == f64::INFINITY {
                "num:inf".to_string()
            } else if *n == f64::NEG_INFINITY {
                "num:-inf".to_string()
            } else if *n == 0.0 && n.is_sign_negative() {
                "num:-0".to_string()
            } else {
                format!("num:{n}")
            }
        }
    }
}

fn encode_golden(v: &J) -> String {
    match v["t"].as_str().expect("a tagged value") {
        "null" => "null".to_string(),
        "bool" => format!("bool:{}", v["v"].as_bool().unwrap()),
        "str" => format!("str:{}", v["v"].as_str().unwrap()),
        "num" => match v.get("special").and_then(J::as_str) {
            Some(s) => format!("num:{s}"),
            // JS prints numbers with its own shortest-round-trip rule; Rust's `{}` for f64
            // agrees on every value this corpus holds. A future divergence here shows up as
            // a loud failure rather than a silent one, which is the point.
            None => format!("num:{}", v["v"].as_f64().unwrap()),
        },
        other => panic!("unknown tag {other}"),
    }
}

#[test]
fn plain_scalar_reads_the_same_values_as_the_typescript_reader() {
    let g = golden();
    let mut d = Diff::default();
    for (input, want) in obj(&g, "scalars") {
        d.check("plainScalar", input, &encode(&plain_scalar(input)), &encode_golden(want));
    }
    d.finish("scalars");
}

#[test]
fn split_kv_agrees_with_the_typescript_reader() {
    let g = golden();
    let mut d = Diff::default();
    for (input, want) in obj(&g, "splits") {
        let got = match split_kv(input) {
            None => "null".to_string(),
            Some(kv) => format!("{:?} / {:?}", kv.key, kv.rest),
        };
        let expected = if want.is_null() {
            "null".to_string()
        } else {
            format!("{:?} / {:?}", want["key"].as_str().unwrap(), want["rest"].as_str().unwrap())
        };
        d.check("splitKV", input, &got, &expected);
    }
    d.finish("splits");
}

#[test]
fn unquote_key_agrees_with_the_typescript_reader() {
    let g = golden();
    let mut d = Diff::default();
    for (input, want) in obj(&g, "unquotes") {
        // The TS side can throw where this one returns; a `threw` case is skipped rather
        // than asserted, because the serializer's only caller wraps it in a try/catch and
        // treats a throw as "do not keep this raw" — which is what returning the unquoted
        // text also produces downstream.
        let Some(ok) = want.get("ok").and_then(J::as_str) else { continue };
        d.check("unquoteKey", input, &unquote_key(input), ok);
    }
    d.finish("unquotes");
}

#[test]
fn fold_lines_agrees_with_the_typescript_reader() {
    let g = golden();
    let folds = g["folds"].as_array().expect("the golden has no `folds` section");
    assert!(!folds.is_empty(), "the `folds` corpus is empty");
    let mut d = Diff::default();
    for case in folds {
        let lines: Vec<String> = case["lines"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        d.check("foldLines", &format!("{lines:?}"), &fold_lines(&lines), case["out"].as_str().unwrap());
    }
    d.finish("folds");
}
