type: array
prefixItems:
- type: string
  x-yamlover:
    concrete: file/yaml
    os:
      path: anyfile01
- type: integer
  x-yamlover:
    concrete: file/yaml
    os:
      path: alsoany02
- type: boolean
  x-yamlover:
    concrete: file/json
    os:
      path: andany03.json
items: false