export { resolveDocument, resolvePointer, pathOf } from './resolve.ts';
export type { Located, ResolvedEdge } from './resolve.ts';
export { buildGraph, deriveInverses, normalize, edgesInto, edgesFrom } from './graph.ts';
export type { Graph, Edge, EdgeKind } from './graph.ts';
export { Store } from './store.ts';
export type { NodeRow, EdgeRow, TocNode, FileRecord, DanglingRef } from './store.ts';
export { walkDir, walkTree, buildIndex, reindex } from './walk.ts';
export type { WalkOptions, WalkResult, IndexDiff } from './walk.ts';
export { planRewrites, applyEdits, nominalPath, under } from './rewrite.ts';
export type { TextEdit, RewritePlan, RewrittenRef, UnrewrittenRef } from './rewrite.ts';
export { mv, relinkMoved } from './mv.ts';
export type { MvReport } from './mv.ts';
export { watchTree } from './watch.ts';
export type { WatchOptions } from './watch.ts';
export { loadSettings, DEFAULT_SETTINGS } from './settings.ts';
export type { Settings } from './settings.ts';
